# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - resume-boost

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:   
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F97B86C4D114417083E6C4A4A2BFECCD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD3304D9AA7A47C797FA3287291CD377 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BF25601FED9B4800912B34020561FE09 }}

      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: resumeboost.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - run: |
          docker build -t resumeboost.azurecr.io/resume-boost:latest .
          docker push resumeboost.azurecr.io/resume-boost:latest

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'resume-boost'
          slot-name: 'Production'
          images: resumeboost.azurecr.io/resume-boost:latest
          